import type { Cafe, EditorialMoment, GuideGroup } from "./types";

export const cafes: Cafe[] = [
  {
    id: "standing-room",
    name: "STANDING ROOM",
    locationText: "蓁巷",
    nearestGate: "南门",
    walkDistanceM: 150,
    walkTimeMin: 2,
    amapPoiId: "B0FFH0E2BG",
    longitude: 118.793343,
    latitude: 32.05248,
    amapAddress: "蓁巷9-3号(近东南大学南门)",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "7:00-16:00",
    weekendHours: "7:00-17:00",
    earlyFriendly: "yes",
    priceLevel: "low",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "quick_coffee",
    tags: ["早八友好", "性价比", "社区感"],
    summary: "南门两分钟内就能买到的一杯稳妥咖啡，是早八前最不费脑子的选择。",
    recommendedItems: ["拿铁", "美式", "鲜榨橙汁"],
    notes:
      "社区店气质很强，鲜榨橙汁是非常明确的记忆点，店员热情，整体适合快速带走或短暂停留。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/standing-room.svg",
    imageGallery: [
      {
        src: "/cafes/standing-room.svg",
        alt: "STANDING ROOM 店铺氛围插画",
        caption: "南门附近的社区小店印象，适合作为早八前的快速选择。",
      },
    ],
  },
  {
    id: "cafe-mo",
    name: "Cafe Mo",
    locationText: "四牌楼南门往西",
    nearestGate: "南门",
    walkDistanceM: 250,
    walkTimeMin: 4,
    amapPoiId: "B0FFF90ZVI",
    longitude: 118.791747,
    latitude: 32.053738,
    entranceLongitude: 118.791732,
    entranceLatitude: 32.05366,
    amapAddress: "四牌楼4-5号",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "8:30-16:00",
    weekendHours: "11:00-16:00",
    earlyFriendly: "maybe",
    priceLevel: "low",
    quietScore: 2,
    socketLevel: "none",
    mainScene: "quick_coffee",
    tags: ["窗口小店", "尝鲜", "奶茶友好"],
    summary: "窗口式小店，适合预算敏感、想买杯不那么无聊饮品的时候顺手带走。",
    recommendedItems: ["拿铁", "奶茶", "小众特饮"],
    notes:
      "无植脂末、性价比高，但营业时间不算稳定，更适合把它当成顺手选项而不是绝对可靠的早八预案。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/cafe-mo.svg",
    imageGallery: [
      {
        src: "/cafes/cafe-mo.svg",
        alt: "Cafe Mo 窗口小店氛围插画",
        caption: "窗口式小店的轻量感，适合预算敏感时顺手带走。",
      },
    ],
  },
  {
    id: "joymean",
    name: "Joymean Coffee",
    locationText: "四牌楼南门往西",
    nearestGate: "南门",
    walkDistanceM: 250,
    walkTimeMin: 4,
    amapPoiId: "B0GKZ64VG9",
    longitude: 118.791722,
    latitude: 32.053779,
    entranceLongitude: 118.791871,
    entranceLatitude: 32.053637,
    amapAddress: "新街口街道四牌楼4-6号",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "7:30-18:00",
    weekendHours: "8:00-16:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["精品友好", "街景感", "日常也能喝"],
    summary: "既能满足日常意式，也能照顾到想喝点更好豆子的人，是兼容度很高的一家。",
    recommendedItems: ["combo 机器手冲", "拿铁", "美式"],
    notes:
      "面向街道的店铺在晴天氛围很好，适合见面聊天或想在普通预算里喝到稍微讲究一点的豆子。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/joymean.svg",
    imageGallery: [
      {
        src: "/cafes/joymean.svg",
        alt: "Joymean Coffee 街景氛围插画",
        caption: "街边店面和精品友好气质，是日常喝感与见面聊天的折中点。",
      },
    ],
  },
  {
    id: "manner",
    name: "Manner（文学客厅店）",
    locationText: "文学客厅",
    nearestGate: "东门",
    walkDistanceM: 450,
    walkTimeMin: 7,
    amapPoiId: "B0LRA90EX0",
    longitude: 118.794323,
    latitude: 32.058123,
    entranceLongitude: 118.794449,
    entranceLatitude: 32.057898,
    amapAddress: "北京东路与鸡鸣寺路交叉口西南80米",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "7:30-17:00",
    weekendHours: "7:30-17:00",
    earlyFriendly: "yes",
    priceLevel: "low",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "quick_coffee",
    tags: ["连锁性价比", "自带杯更划算", "稳定"],
    summary: "如果只想买一杯简单、稳定、性价比不错的意式，Manner 是很稳的连锁答案。",
    recommendedItems: ["小杯美式", "拿铁", "SOE"],
    notes:
      "自带杯减 5 元非常实用，虽然不算最近，但连锁品质稳定，适合舍想踩坑的日常购买。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/manner.svg",
    imageGallery: [
      {
        src: "/cafes/manner.svg",
        alt: "Manner 文学客厅店氛围插画",
        caption: "连锁店的稳定感和文学客厅位置，适合日常不想踩坑的一杯。",
      },
    ],
  },
  {
    id: "disc-coffee",
    name: "Disc Coffee",
    locationText: "成贤街",
    nearestGate: "东门",
    walkDistanceM: 70,
    walkTimeMin: 1,
    longitude: 118.796052,
    latitude: 32.054529,
    amapAddress: "成贤街112号大院附近",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "9:00-17:00",
    weekendHours: "9:30-17:00",
    earlyFriendly: "no",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["文艺氛围", "东门极近", "特色豆"],
    summary: "东门外一步之遥，电影海报和黑胶气质很鲜明，是很容易让人想停下来坐一会的店。",
    recommendedItems: ["蜜瓜冻拿铁", "美式", "中烘豆"],
    notes:
      "氛围非常完整，基础咖啡也能选中烘，对不喜欢深烘焦苦感的人很友好，适合聊天和轻度停留。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/disc-coffee.svg",
    imageGallery: [
      {
        src: "/cafes/disc-coffee.svg",
        alt: "Disc Coffee 文艺氛围插画",
        caption: "电影海报和黑胶气质更鲜明，适合轻度停留和聊天。",
      },
    ],
  },
  {
    id: "umber",
    name: "umber",
    locationText: "珠江路",
    nearestGate: "南门",
    walkDistanceM: 500,
    walkTimeMin: 8,
    amapPoiId: "B0I6JU1MWT",
    longitude: 118.792376,
    latitude: 32.049452,
    entranceLongitude: 118.792397,
    entranceLatitude: 32.049357,
    amapAddress: "珠江路277号(浮桥地铁站2号口步行360米)",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "8:00-17:30",
    weekendHours: "8:00-18:30",
    earlyFriendly: "maybe",
    priceLevel: "high",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["特调精品", "手冲友好", "预算更高"],
    summary: "不是最近的一家，但如果你就是想喝点更好的豆子或特调，它值得专门走过去。",
    recommendedItems: ["特调咖啡", "烘焙", "combo"],
    notes:
      "单品豆和特调都更丰富，价格更高，适合预算充足且明确想喝点不一样的人，不适合追求极致效率。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/umber.svg",
    imageGallery: [
      {
        src: "/cafes/umber.svg",
        alt: "umber 特调精品氛围插画",
        caption: "预算更高但风味感更明确，适合为了特调和豆子专门走一趟。",
      },
    ],
  },
  {
    id: "clip-coffee",
    name: "clip coffee",
    locationText: "双井巷",
    nearestGate: "南门",
    walkDistanceM: 350,
    walkTimeMin: 5,
    amapPoiId: "B0FFKOF7NY",
    longitude: 118.792958,
    latitude: 32.050623,
    entranceLongitude: 118.792865,
    entranceLatitude: 32.050626,
    amapAddress: "双井巷1号(浮桥地铁站1号口步行440米)",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "7:30-17:00",
    weekendHours: "8:00-19:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["特调", "设计感", "转角小店"],
    summary: "白色转角店面和克制的空间设计很有记忆点，适合想坐一下、也想获得一点视觉愉悦的人。",
    recommendedItems: ["特调咖啡", "烘焙", "文创周边"],
    notes:
      "老店气质明显，店面设计有想法，还有文创与烘焙延展，整体很适合做页面里的编辑精选。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/clip-coffee.svg",
    imageGallery: [
      {
        src: "/cafes/clip-coffee.svg",
        alt: "clip coffee 转角小店氛围插画",
        caption: "白色转角店面的设计感，适合坐一下也适合被记住。",
      },
    ],
  },
  {
    id: "katherine-starbucks",
    name: "凯瑟琳星巴克",
    locationText: "凯瑟琳广场",
    nearestGate: "校区外步行可达",
    walkDistanceM: 550,
    walkTimeMin: 8,
    amapPoiId: "B0FFG4AZ3Y",
    longitude: 118.787325,
    latitude: 32.059575,
    entranceLongitude: 118.787003,
    entranceLatitude: 32.059292,
    amapAddress: "北京东路1号环亚凯瑟琳广场1-2层G-01铺位",
    poiVerifiedAt: "2026-05-16",
    weekdayHours: "6:30-22:00",
    weekendHours: "6:30-22:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 4,
    socketLevel: "good",
    mainScene: "study",
    tags: ["学习友好", "营业时间长", "插座更稳"],
    summary: "如果需求从喝咖啡变成找一个能待很久的地方，自习属性最强的仍然是它。",
    recommendedItems: ["冰美式", "拿铁", "轻食"],
    notes:
      "双层空间让它比周边很多店更像临时自习室，插座不算特别多但够用，夜间停留也更从容。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/katherine-starbucks.svg",
    imageGallery: [
      {
        src: "/cafes/katherine-starbucks.svg",
        alt: "凯瑟琳星巴克学习空间氛围插画",
        caption: "双层空间和长营业时间，让它更像临时学习/工作点。",
      },
    ],
  },
];

export const guideGroups: GuideGroup[] = [
  {
    id: "early",
    label: "早八友好",
    kicker: "赶时间",
    description: "离门近、开门早、带走效率高，适合未来 30 分钟内就要进教室的人。",
  },
  {
    id: "study",
    label: "学习友好",
    kicker: "能久坐",
    description: "更适合坐下来自习、改稿、充电，空间稳定性比单杯风味更重要。",
  },
  {
    id: "chat",
    label: "聊天友好",
    kicker: "适合见面",
    description: "适合和朋友碰面、简单坐坐，氛围和距离感要比绝对安静更重要。",
  },
  {
    id: "specialty",
    label: "特调精品",
    kicker: "想喝好点",
    description: "当需求从提神变成“想喝点不一样”，这组会更有意思。",
  },
  {
    id: "editorial",
    label: "文艺氛围",
    kicker: "氛围感",
    description: "更适合被拍下来、被记住，也更适合做你的校园生活方式地图。",
  },
];

export const editorialMoments: EditorialMoment[] = [
  {
    title: "最适合早八的一杯",
    body: "如果你只想在最短时间里获得最稳妥的提神答案，Standing Room 仍然是南门的默认正确项。",
    cafeId: "standing-room",
  },
  {
    title: "最适合自习的一家",
    body: "当需求从咖啡变成临时工作空间时，凯瑟琳星巴克的长营业时间和插座稳定性会迅速拉开差距。",
    cafeId: "katherine-starbucks",
  },
  {
    title: "最适合喝点不一样的人",
    body: "umber 不是离学校最近的一家，但它把“专门为一杯咖啡多走几分钟”这件事变得合理了。",
    cafeId: "umber",
  },
];
