import type { Cafe, EditorialMoment, GuideGroup } from "./types";

export const cafes: Cafe[] = [
  {
    id: "standing-room",
    name: "STANDING ROOM",
    locationText: "蓁巷",
    nearestGate: "南门",
    walkDistanceM: 150,
    walkTimeMin: 2,
    weekdayHours: "7:00-16:00",
    weekendHours: "7:00-17:00",
    earlyFriendly: "yes",
    priceLevel: "low",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "quick_coffee",
    tags: ["早八友好", "性价比", "社区感"],
    summary: "南门两分钟内就能买到的一杯稳妥咖啡，是早八前最不费脑子的选择。",
    recommendedItems: ["拿铁", "美式", "鲜榨橙汁"],
    notes:
      "社区店气质很强，鲜榨橙汁是非常明确的记忆点，店员热情，整体适合快速带走或短暂停留。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/standing-room.svg",
  },
  {
    id: "cafe-mo",
    name: "Cafe Mo",
    locationText: "四牌楼南门往西",
    nearestGate: "南门",
    walkDistanceM: 250,
    walkTimeMin: 4,
    weekdayHours: "8:30-16:00",
    weekendHours: "11:00-16:00",
    earlyFriendly: "maybe",
    priceLevel: "low",
    quietScore: 2,
    socketLevel: "none",
    mainScene: "quick_coffee",
    tags: ["窗口小店", "尝鲜", "奶茶友好"],
    summary: "窗口式小店，适合预算敏感、想买杯不那么无聊饮品的时候顺手带走。",
    recommendedItems: ["拿铁", "奶茶", "小众特饮"],
    notes:
      "无植脂末、性价比高，但营业时间不算稳定，更适合把它当成顺手选项而不是绝对可靠的早八预案。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/cafe-mo.svg",
  },
  {
    id: "joymean",
    name: "Joymean Coffee",
    locationText: "四牌楼南门往西",
    nearestGate: "南门",
    walkDistanceM: 250,
    walkTimeMin: 4,
    weekdayHours: "7:30-18:00",
    weekendHours: "8:00-16:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["精品友好", "街景感", "日常也能喝"],
    summary: "既能满足日常意式，也能照顾到想喝点更好豆子的人，是兼容度很高的一家。",
    recommendedItems: ["combo 机器手冲", "拿铁", "美式"],
    notes:
      "面向街道的店铺在晴天氛围很好，适合见面聊天或想在普通预算里喝到稍微讲究一点的豆子。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/joymean.svg",
  },
  {
    id: "manner",
    name: "Manner（文学客厅店）",
    locationText: "文学客厅",
    nearestGate: "东门",
    walkDistanceM: 450,
    walkTimeMin: 7,
    weekdayHours: "7:30-17:00",
    weekendHours: "7:30-17:00",
    earlyFriendly: "yes",
    priceLevel: "low",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "quick_coffee",
    tags: ["连锁性价比", "自带杯更划算", "稳定"],
    summary: "如果只想买一杯简单、稳定、性价比不错的意式，Manner 是很稳的连锁答案。",
    recommendedItems: ["小杯美式", "拿铁", "SOE"],
    notes:
      "自带杯减 5 元非常实用，虽然不算最近，但连锁品质稳定，适合舍想踩坑的日常购买。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/manner.svg",
  },
  {
    id: "disc-coffee",
    name: "Disc Coffee",
    locationText: "成贤街",
    nearestGate: "东门",
    walkDistanceM: 70,
    walkTimeMin: 1,
    weekdayHours: "9:00-17:00",
    weekendHours: "9:30-17:00",
    earlyFriendly: "no",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["文艺氛围", "东门极近", "特色豆"],
    summary: "东门外一步之遥，电影海报和黑胶气质很鲜明，是很容易让人想停下来坐一会的店。",
    recommendedItems: ["蜜瓜冻拿铁", "美式", "中烘豆"],
    notes:
      "氛围非常完整，基础咖啡也能选中烘，对不喜欢深烘焦苦感的人很友好，适合聊天和轻度停留。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/disc-coffee.svg",
  },
  {
    id: "umber",
    name: "umber",
    locationText: "珠江路",
    nearestGate: "南门",
    walkDistanceM: 500,
    walkTimeMin: 8,
    weekdayHours: "8:00-17:30",
    weekendHours: "8:00-18:30",
    earlyFriendly: "maybe",
    priceLevel: "high",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["特调精品", "手冲友好", "预算更高"],
    summary: "不是最近的一家，但如果你就是想喝点更好的豆子或特调，它值得专门走过去。",
    recommendedItems: ["特调咖啡", "烘焙", "combo"],
    notes:
      "单品豆和特调都更丰富，价格更高，适合预算充足且明确想喝点不一样的人，不适合追求极致效率。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/umber.svg",
  },
  {
    id: "clip-coffee",
    name: "clip coffee",
    locationText: "双井巷",
    nearestGate: "南门",
    walkDistanceM: 350,
    walkTimeMin: 5,
    weekdayHours: "7:30-17:00",
    weekendHours: "8:00-19:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 3,
    socketLevel: "limited",
    mainScene: "chat",
    tags: ["特调", "设计感", "转角小店"],
    summary: "白色转角店面和克制的空间设计很有记忆点，适合想坐一下、也想获得一点视觉愉悦的人。",
    recommendedItems: ["特调咖啡", "烘焙", "文创周边"],
    notes:
      "老店气质明显，店面设计有想法，还有文创与烘焙延展，整体很适合做页面里的编辑精选。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/clip-coffee.svg",
  },
  {
    id: "katherine-starbucks",
    name: "凯瑟琳星巴克",
    locationText: "凯瑟琳广场",
    nearestGate: "校区外步行可达",
    walkDistanceM: 550,
    walkTimeMin: 8,
    weekdayHours: "6:30-22:00",
    weekendHours: "6:30-22:00",
    earlyFriendly: "yes",
    priceLevel: "medium",
    quietScore: 4,
    socketLevel: "good",
    mainScene: "study",
    tags: ["学习友好", "营业时间长", "插座更稳"],
    summary: "如果需求从喝咖啡变成找一个能待很久的地方，自习属性最强的仍然是它。",
    recommendedItems: ["冰美式", "拿铁", "轻食"],
    notes:
      "双层空间让它比周边很多店更像临时自习室，插座不算特别多但够用，夜间停留也更从容。",
    sourceNote: "《四牌楼咖啡指北》一手观察",
    verifiedAt: "2026-04-03",
    coverImage: "/cafes/katherine-starbucks.svg",
  },
];

export const guideGroups: GuideGroup[] = [
  {
    id: "early",
    label: "早八友好",
    kicker: "赶时间",
    description: "离门近、开门早、带走效率高，适合未来 30 分钟内就要进教室的人。",
  },
  {
    id: "study",
    label: "学习友好",
    kicker: "能久坐",
    description: "更适合坐下来自习、改稿、充电，空间稳定性比单杯风味更重要。",
  },
  {
    id: "chat",
    label: "聊天友好",
    kicker: "适合见面",
    description: "适合和朋友碰面、简单坐坐，氛围和距离感要比绝对安静更重要。",
  },
  {
    id: "specialty",
    label: "特调精品",
    kicker: "想喝好点",
    description: "当需求从提神变成“想喝点不一样”，这组会更有意思。",
  },
  {
    id: "editorial",
    label: "文艺氛围",
    kicker: "氛围感",
    description: "更适合被拍下来、被记住，也更适合做你的校园生活方式地图。",
  },
];

export const editorialMoments: EditorialMoment[] = [
  {
    title: "最适合早八的一杯",
    body: "如果你只想在最短时间里获得最稳妥的提神答案，Standing Room 仍然是南门的默认正确项。",
    cafeId: "standing-room",
  },
  {
    title: "最适合自习的一家",
    body: "当需求从咖啡变成临时工作空间时，凯瑟琳星巴克的长营业时间和插座稳定性会迅速拉开差距。",
    cafeId: "katherine-starbucks",
  },
  {
    title: "最适合喝点不一样的人",
    body: "umber 不是离学校最近的一家，但它把“专门为一杯咖啡多走几分钟”这件事变得合理了。",
    cafeId: "umber",
  },
];
